### ISSUE TITLE
There is a misspelling where should be `unrar`

### ISSUE THREAD

**Issue by datsfilipe** [Manas140/sh#6]
In the `ext` script, `unar` is written instead of `unrar`, as shown here:
``` shell
case "$@" in
    *.rar) unar x "$@" -o "$dir";
```
I noticed today when using it.

**Comment by Manas140** [comment]
Oh, there aren't many who open an issue so I never noticed I'll fix it right away,
Thanks! 😄

**Comment by Manas140** [comment]
The program is called unrar and not unar...

**Comment by datsfilipe** [comment]
> The program is called unrar and not unar...

I know, that's what I said. In your script, it's written `unar`.

**Comment by Manas140** [comment]
Oh, I'm sorry for the previous misunderstanding. I meant that the program is called unar and not unrar
![image](https://github.com/Manas140/sh/assets/64472354/1fa495d1-0dda-4576-a367-6c30510e2d95)

**Comment by datsfilipe** [comment]
I didn't know this one, sorry to bother you with this.
